### ISSUE TITLE
How do I get in touch with the author?

### ISSUE THREAD

**Issue by derekchiang** [doublespending/MEVBoostAA#1]
Hi @doublespending, what you are working on is fascinating and I'd love to get in touch.  I'm the founder of [ZeroDev](https://zerodev.app/) which develops [Kernel](https://github.com/zerodevapp/kernel).  I think there can be strong synergies between what we are working on.

If you can send me an email at `derek at zerodev.app`, that'd be great.  Or `@derek_chiang` on TG.

**Comment by doublespending** [comment]
Nice to meet you. I have sent a email to you. Looking forward to further communication～
